name: Frontend Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
   
    - uses: actions/checkout@v2
      
    - name: eko
      run: echo $FRONTEND_PRIVATE_KEY
      env:
        FRONTEND_PRIVATE_KEY: MIIEpgIBAAKCAQEAm4KahDK0seF/Nb8HnmTwHM0HUtqaCpgJu09DVBtwlhQAsF9eC5V/fRBeO+QvTYndViQ6VqI6bOatHWoBnbn11NANf892HPdrl0HrKKImT1yV+fYUWQktvlVf9tSuu4iLhkVp4cZf4gJIg/F/JgGR4fs42KWaXUTsgmOdQr969m3u2kBgb58ClQAWtk5xHziUDql3z6ydekdBjrAJ305kRz5VZhH4s40TxAjbFk7Bn0qF44DOjsvIpDWTP0GZP3Yyml4rjF82VVC2dzmnY1BGPbdllNSqtn+u725etp3zCVwjvpDC8tHdg3JtwLlhqR+aA4PssjDaQI2h5DgBPTui8QIDAQABAoIBAQCGb9HEl1E+tgKTJCIh/IDXZSf/qJuirO080LkT7OTX2VL/JnLW8NbV92B/xjReg+Ckp40HeBeqLYFa/FmJUUoEQBhrdZ5WTE7m5EW3SvZzhUbiYKoWjqjM8mGTsSmdVd3Iphly5VvetrqZ1hxlbtX+1n++Suu31e3git1Y5tAWWHkFy3d0DKR9uKa0Rjnu1s2rpryM3+KtiKs6lPWXtIjSVJVLaj+yazifeZTqFAFwM2RahRUIK7sI91guVMjH9gT4ETlYhbMydLHIs2BWMSdtAGckWFJo3Z0q1ddkvinNa3pwe4CB2Mbqk1vAzQ9lcErC1nzvUMi0YNHPHfE4h4tBAoGBANjjgZnIIMXHp/ZjLjOFsaVd1kQv4ssoomD5q/5Xcw98PKWOl1dz4PEimhOQbjqOtudqBtYhwdD9CvB1/aog3RHPOeqfnlzAPAOdAcOXQbyxKkdGuEFKyTvvFLrzss+XExuHSMY6xNBq41O3k1wqvNZzoV3Bk/Z34VDIdRX07qYvAoGBALeNm0qGN+1f1CqIRv/WCRS1Eg/kxlp2wL5xlwWeFAJFtF44NoyWTlFJE70rCHSJuQw6rlCRLvfrw8DocEqpMedBLEWm/fWYqPVgYFWxOm6Ex7tPfK3zs4e2TjT0xxHA/eGOTHcOQhOo4znBPxt12zVE+xFV6OitOttELQxK3SDfAoGBAJr02HhtknSb8/XF4JFw+H3kcBxhdhCeJH1ShD6AbjVnFtFV8ezKXrEJfrlxnD98DVOC3gWJMrdEwtcQBb7SIgACZSerCPLNaVNPjp4WaCIPFdy8uxHzA5ktdEspp9xG3KDzY9w0yr75TxdV9hOIeUhibqzUjAkwlysnPPgF+aeDAoGBALKZPrjM0C5QSAj6gNr+T+euJ9z/JWFwmyqzK9dzcNSlLlNfLvSsa5f8GxC9hoSeXUfg8SvDmIfzB430nQ6Igt4ZNBKx4fnOiNf45sN6pvhSimVfelln/w/V+1Lbubc0qdOGujA91115v167AcSecKTscb70cKO1qscfFxYW4gLRAoGBAKuWOx/3lFmskoHGMED9o8VCdivM4lBgnzyt89E3rTdXFkHhAuR13nrzHcG3Kn+xKAvkuK4DN6HPaaz7GMi+LWo6daLKaKbcZ2vWZlAiYDr0VeChITxnmohpSxOixmoe/VqE0fAdG7NgCmuCecZWTpsGQ4UzIeH0LIcgl8Mk5GSE
      
    - name: Clear the machine
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-17-180-100.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: $FRONTEND_PRIVATE_KEY
        script_stop: true
        script: | 
          sudo rm -rf ~/app || true
          sudo docker container stop $(sudo docker container ls -aq) || true
          docker system prune –af ––volumes || true
          mkdir ~/app
      env:
        FRONTEND_PRIVATE_KEY: MIIEpgIBAAKCAQEAm4KahDK0seF/Nb8HnmTwHM0HUtqaCpgJu09DVBtwlhQAsF9eC5V/fRBeO+QvTYndViQ6VqI6bOatHWoBnbn11NANf892HPdrl0HrKKImT1yV+fYUWQktvlVf9tSuu4iLhkVp4cZf4gJIg/F/JgGR4fs42KWaXUTsgmOdQr969m3u2kBgb58ClQAWtk5xHziUDql3z6ydekdBjrAJ305kRz5VZhH4s40TxAjbFk7Bn0qF44DOjsvIpDWTP0GZP3Yyml4rjF82VVC2dzmnY1BGPbdllNSqtn+u725etp3zCVwjvpDC8tHdg3JtwLlhqR+aA4PssjDaQI2h5DgBPTui8QIDAQABAoIBAQCGb9HEl1E+tgKTJCIh/IDXZSf/qJuirO080LkT7OTX2VL/JnLW8NbV92B/xjReg+Ckp40HeBeqLYFa/FmJUUoEQBhrdZ5WTE7m5EW3SvZzhUbiYKoWjqjM8mGTsSmdVd3Iphly5VvetrqZ1hxlbtX+1n++Suu31e3git1Y5tAWWHkFy3d0DKR9uKa0Rjnu1s2rpryM3+KtiKs6lPWXtIjSVJVLaj+yazifeZTqFAFwM2RahRUIK7sI91guVMjH9gT4ETlYhbMydLHIs2BWMSdtAGckWFJo3Z0q1ddkvinNa3pwe4CB2Mbqk1vAzQ9lcErC1nzvUMi0YNHPHfE4h4tBAoGBANjjgZnIIMXHp/ZjLjOFsaVd1kQv4ssoomD5q/5Xcw98PKWOl1dz4PEimhOQbjqOtudqBtYhwdD9CvB1/aog3RHPOeqfnlzAPAOdAcOXQbyxKkdGuEFKyTvvFLrzss+XExuHSMY6xNBq41O3k1wqvNZzoV3Bk/Z34VDIdRX07qYvAoGBALeNm0qGN+1f1CqIRv/WCRS1Eg/kxlp2wL5xlwWeFAJFtF44NoyWTlFJE70rCHSJuQw6rlCRLvfrw8DocEqpMedBLEWm/fWYqPVgYFWxOm6Ex7tPfK3zs4e2TjT0xxHA/eGOTHcOQhOo4znBPxt12zVE+xFV6OitOttELQxK3SDfAoGBAJr02HhtknSb8/XF4JFw+H3kcBxhdhCeJH1ShD6AbjVnFtFV8ezKXrEJfrlxnD98DVOC3gWJMrdEwtcQBb7SIgACZSerCPLNaVNPjp4WaCIPFdy8uxHzA5ktdEspp9xG3KDzY9w0yr75TxdV9hOIeUhibqzUjAkwlysnPPgF+aeDAoGBALKZPrjM0C5QSAj6gNr+T+euJ9z/JWFwmyqzK9dzcNSlLlNfLvSsa5f8GxC9hoSeXUfg8SvDmIfzB430nQ6Igt4ZNBKx4fnOiNf45sN6pvhSimVfelln/w/V+1Lbubc0qdOGujA91115v167AcSecKTscb70cKO1qscfFxYW4gLRAoGBAKuWOx/3lFmskoHGMED9o8VCdivM4lBgnzyt89E3rTdXFkHhAuR13nrzHcG3Kn+xKAvkuK4DN6HPaaz7GMi+LWo6daLKaKbcZ2vWZlAiYDr0VeChITxnmohpSxOixmoe/VqE0fAdG7NgCmuCecZWTpsGQ4UzIeH0LIcgl8Mk5GSE
    
    - name: Build the Docker Image
      run: docker build -t webimage web
    
    - name: Save the Docker Image
      run: docker save webimage | gzip > webimage.tar.gz
   
#     - name: Clear the machine
#       uses: appleboy/ssh-action@master
#       with:
#         host: ec2-3-17-180-100.us-east-2.compute.amazonaws.com
#         username: ubuntu
#         key: $FRONTEND_PRIVATE_KEY
#         script_stop: true
#         script: | 
#           sudo rm -rf ~/app || true
#           sudo docker container stop $(sudo docker container ls -aq) || true
#           docker system prune –af ––volumes || true
#           mkdir ~/app
#       env:
#         FRONTEND_PRIVATE_KEY: ${{ secrets.FRONTEND_PRIVATE_KEY }}  
    
    - name: Push Docker Image to AWS
      uses: appleboy/scp-action@master
      with:
        host: ec2-3-17-180-100.us-east-2.compute.amazonaws.com
        key: $FRONTEND_PRIVATE_KEY
        username: ubuntu
        source: webimage.tar.gz
        target: ~/app/
    
    - name: Run Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-17-180-100.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: $FRONTEND_PRIVATE_KEY
        script_stop: true
        script: | 
          cd ~/app
          sudo docker load -i webimage.tar.gz
          sudo docker run -p 80:80 
